const AUTO_ROLE_ERROR_CODES = Object.freeze({
  VALIDATION: "AUTO_ROLE_VALIDATION",
  CONFIG_NOT_FOUND: "AUTO_ROLE_CONFIG_NOT_FOUND",
  DISABLED: "AUTO_ROLE_DISABLED",
  RULE_NOT_FOUND: "AUTO_ROLE_RULE_NOT_FOUND",
  FORBIDDEN: "AUTO_ROLE_FORBIDDEN",
  INELIGIBLE: "AUTO_ROLE_INELIGIBLE",
  UNMANAGEABLE: "AUTO_ROLE_UNMANAGEABLE",
  CONFLICT: "AUTO_ROLE_CONFLICT",
  OPERATION_PARTIAL: "AUTO_ROLE_OPERATION_PARTIAL",
  LEASE_LOST: "AUTO_ROLE_LEASE_LOST",
  RATE_LIMIT: "AUTO_ROLE_RATE_LIMIT",
  TRANSIENT: "AUTO_ROLE_TRANSIENT",
});
const AUTO_ROLE_RESULT_CODES = Object.freeze({
  CONFIGURED: "AUTO_ROLE_CONFIGURED",
  CONFIG_READ: "AUTO_ROLE_CONFIG_READ",
  ENABLED: "AUTO_ROLE_ENABLED",
  DISABLED: "AUTO_ROLE_DISABLED_RESULT",
  RULE_CREATED: "AUTO_ROLE_RULE_CREATED",
  RULE_READ: "AUTO_ROLE_RULE_READ",
  RULE_UPDATED: "AUTO_ROLE_RULE_UPDATED",
  RULE_DELETED: "AUTO_ROLE_RULE_DELETED",
  PLAN_READY: "AUTO_ROLE_PLAN_READY",
  DRY_RUN: "AUTO_ROLE_DRY_RUN",
  APPLIED: "AUTO_ROLE_APPLIED",
  ALREADY_ASSIGNED: "AUTO_ROLE_ALREADY_ASSIGNED",
  SKIPPED: "AUTO_ROLE_SKIPPED",
  SCAN_QUEUED: "AUTO_ROLE_SCAN_QUEUED",
  SCAN_BATCH_PROCESSED: "AUTO_ROLE_SCAN_BATCH_PROCESSED",
});
class AutoRoleError extends Error {
  constructor(message, code, details = {}) { super(message); this.name = this.constructor.name; this.code = code; this.details = Object.freeze({ ...details }); }
}
class AutoRoleValidationError extends AutoRoleError {}
class AutoRoleAuthorizationError extends AutoRoleError {}
class AutoRoleStateError extends AutoRoleError {}
module.exports = { AUTO_ROLE_ERROR_CODES, AUTO_ROLE_RESULT_CODES, AutoRoleError, AutoRoleValidationError, AutoRoleAuthorizationError, AutoRoleStateError };
