class ModerationError extends Error {
  constructor(code, message, metadata = {}) {
    super(message);
    this.name = "ModerationError";
    this.code = code;
    this.metadata = metadata;
  }
}

const ModerationErrorCodes = Object.freeze({
  GUILD_ONLY: "MODERATION_GUILD_ONLY",
  INVALID_INPUT: "MODERATION_INVALID_INPUT",
  ACTOR_PERMISSION: "MODERATION_ACTOR_PERMISSION",
  BOT_PERMISSION: "MODERATION_BOT_PERMISSION",
  TARGET_NOT_MEMBER: "MODERATION_TARGET_NOT_MEMBER",
  TARGET_SELF: "MODERATION_TARGET_SELF",
  TARGET_BOT: "MODERATION_TARGET_BOT",
  TARGET_OWNER: "MODERATION_TARGET_OWNER",
  ACTOR_HIERARCHY: "MODERATION_ACTOR_HIERARCHY",
  BOT_HIERARCHY: "MODERATION_BOT_HIERARCHY",
  TARGET_NOT_CAPABLE: "MODERATION_TARGET_NOT_CAPABLE",
  NOT_BANNED: "MODERATION_NOT_BANNED",
  NOT_TIMED_OUT: "MODERATION_NOT_TIMED_OUT",
  PROVIDER_FAILURE: "MODERATION_PROVIDER_FAILURE",
});

module.exports = { ModerationError, ModerationErrorCodes };
