const { PermissionFlagsBits } = require("discord.js");
const MemberRoleGateway = require("../../../application/repositories/contracts/MemberRoleGateway");
const { AUTO_ROLE_ERROR_CODES: CODES, AutoRoleStateError } = require("../../../domain/errors/AutoRoleErrors");
class DiscordMemberRoleGateway extends MemberRoleGateway {
  constructor(client) { super(); this.client = client; }
  async getActorFacts({ guildId, actorId }) { const guild = await this._guild(guildId); const actor = await this._member(guild, actorId); return { guildId, actorId, actorIsOwner: actorId === guild.ownerId, actorIsAdministrator: Boolean(actor?.permissions?.has?.(PermissionFlagsBits.Administrator)) }; }
  async getMemberFacts({ guildId, userId, actorId = null }) { const guild = await this._guild(guildId); const [target, bot, actor] = await Promise.all([this._member(guild, userId), this._member(guild, this.client.user.id), actorId ? this._member(guild, actorId) : null]); if (!target) return null; const roles = [...target.roles.cache.values()]; const botHighest = bot?.roles?.highest; return { guildId, userId, actorId, targetIsBot: Boolean(target.user?.bot), targetIsOwner: userId === guild.ownerId, targetManageable: Boolean(target.manageable), actorIsOwner: actorId === guild.ownerId, actorIsAdministrator: Boolean(actor?.permissions?.has?.(PermissionFlagsBits.Administrator)), botHasManageRoles: Boolean(bot?.permissions?.has?.(PermissionFlagsBits.ManageRoles)), currentRoleIds: roles.map((role) => role.id), manageableRoleIds: [...guild.roles.cache.values()].filter((role) => role.id !== guild.id && !role.managed && botHighest?.comparePositionTo?.(role) > 0).map((role) => role.id), exclusiveGroupRoleIds: {}, owningPriorityByRole: {} }; }
  async listMembersPage({ guildId, after = null, limit = 1000 }) { const guild = await this._guild(guildId); const bounded = Math.max(1, Math.min(1000, Number.isInteger(limit) ? limit : 1000)); const members = [...(await guild.members.list({ after: after || undefined, limit: bounded, cache: false })).values()].map((member) => ({ userId: member.id, bot: Boolean(member.user?.bot), roleIds: [...member.roles.cache.keys()] })); return { members, nextCursor: members.length === bounded ? members.at(-1)?.userId || null : null }; }
  async addRole({ guildId, userId, roleId, reason }) { const member = await this._requiredMember(guildId, userId); try { await member.roles.add(roleId, boundedReason(reason)); return true; } catch (error) { throw providerError(error); } }
  async removeRole({ guildId, userId, roleId, reason }) { const member = await this._requiredMember(guildId, userId); try { await member.roles.remove(roleId, boundedReason(reason)); return true; } catch (error) { throw providerError(error); } }
  async refetchMember({ guildId, userId }) { const guild = await this._guild(guildId); const member = await this._member(guild, userId); return member ? { guildId, userId, roleIds: [...member.roles.cache.keys()] } : null; }
  async _requiredMember(guildId, userId) { const member = await this._member(await this._guild(guildId), userId); if (!member) throw new AutoRoleStateError("Member was not found.", CODES.INELIGIBLE); return member; }
  async _guild(guildId) { try { return this.client.guilds.cache.get(guildId) || await this.client.guilds.fetch(guildId); } catch (error) { throw providerError(error); } }
  async _member(guild, userId) { try { return await guild.members.fetch({ user: userId, force: true }); } catch (error) { if (error?.status === 404 || error?.code === 10007) return null; throw providerError(error); } }
}
function boundedReason(value) { return String(value || "Member Automation Auto Role").replace(/[\r\n]/g, " ").slice(0, 512); }
function providerError(error) { const mapped = error?.status === 429 ? CODES.RATE_LIMIT : Number(error?.status) >= 500 ? CODES.TRANSIENT : CODES.UNMANAGEABLE; return new AutoRoleStateError("Discord could not complete the Auto Role operation.", mapped, { providerCode: String(error?.code || error?.status || "UNKNOWN").replace(/[^A-Za-z0-9_.:-]/g, "_").slice(0, 64) }); }
module.exports = DiscordMemberRoleGateway; module.exports.providerError = providerError;
