require("module-alias/register"); const test = require("node:test"); const assert = require("node:assert/strict"); const { PermissionFlagsBits, MessageFlags } = require("discord.js");
const command = require("../../src/interfaces/discord/commands/admin/auto-role/command"); const { AutoRoleHandler } = require("../../src/interfaces/discord/commands/admin/auto-role/handler"); const component = require("../../src/interfaces/discord/commands/admin/auto-role/components"); const AutoRoleComponentAdapter = require("../../src/interfaces/discord/adapters/AutoRoleComponentAdapter"); const DiscordMemberRoleGateway = require("../../src/infrastructure/providers/discord/DiscordMemberRoleGateway");
function interaction(sub, values = {}) { const calls=[]; return { calls, value:{ id:"333333333333333333", guildId:"111111111111111111", guild:{ownerId:"owner"}, user:{id:"222222222222222222"}, deferred:false, replied:false, inGuild:()=>true, memberPermissions:{has:(p)=>p===PermissionFlagsBits.Administrator}, options:{getSubcommand:()=>sub,getString:(n)=>values[n]??null,getBoolean:(n)=>values[n]??null,getInteger:(n)=>values[n]??null,getRole:(n)=>values[n]??null,getUser:(n)=>values[n]??null}, async deferReply(p){calls.push(["defer",p]);this.deferred=true;},async editReply(p){calls.push(["edit",p]);} } }; }
test("autorole schema is Administrator guild-only and complete",()=>{const json=command.data.toJSON();assert.equal(json.dm_permission,false);assert.equal(json.default_member_permissions,PermissionFlagsBits.Administrator.toString());assert.deepEqual(json.options.map(x=>x.name),["setup","rule-create","rule-edit","rule-delete","rule-enable","rule-disable","rule-list","rule-view","scan","scan-status","repair","preview","config"]);});
test("scan only queues and acknowledges exactly once ephemerally",async()=>{const fixture=interaction("scan",{"dry-run":true,"missing-only":false});let dto;const services={autoRoleScanService:{async enqueue(v){dto=v;}},autoRoleRuleService:{},autoRoleService:{}};await new AutoRoleHandler().execute({interaction:fixture.value,container:{resolve:()=>services}});assert.deepEqual(fixture.calls[0],["defer",{flags:MessageFlags.Ephemeral}]);assert.equal(fixture.calls.filter(x=>x[0]==="defer").length,1);assert.equal(dto.dryRun,true);assert.equal(dto.missingOnly,false);assert.equal(Object.values(dto).some(v=>v&&typeof v==="object"),false);});
test("runtime admin denial happens before service resolution",async()=>{const fixture=interaction("rule-list");fixture.value.memberPermissions.has=()=>false;let resolved=false;await new AutoRoleHandler().execute({interaction:fixture.value,container:{resolve(){resolved=true;}}});assert.equal(resolved,false);});
test("component custom IDs are bounded and reject malformed input",()=>{assert.deepEqual(component.parse("ma:autorole:session_123:confirm"),{sessionId:"session_123",action:"confirm"});assert.equal(component.parse("ma:autorole:x:confirm"),null);assert.equal(component.parse("ma:autorole:session_123:delete-all"),null);});
test("component adapter enforces owner guild expiry and current admin",async()=>{const replies=[];const adapter=new AutoRoleComponentAdapter({sessionRepository:{findById:async()=>({sessionId:"session_123",status:"ACTIVE",expiresAt:200,guildId:"guild",ownerId:"owner"})},clock:{now:()=>100}});await adapter.handle({guildId:"wrong",user:{id:"owner"},guild:{ownerId:"owner"},memberPermissions:{has:()=>true},reply:async(p)=>replies.push(p)},{sessionId:"session_123",action:"next"});assert.equal(replies[0].flags,MessageFlags.Ephemeral);});
test("Discord gateway refetches member and returns primitive role facts",async()=>{const fetched=[];const role={id:"role",managed:false};const member={id:"user",user:{bot:false},manageable:true,permissions:{has:()=>true},roles:{cache:new Map([["role",role]]),highest:{comparePositionTo:()=>1}}};const bot={...member,id:"bot"};const guild={id:"guild",ownerId:"owner",members:{fetch:async(q)=>{fetched.push(q);return q.user==="bot"?bot:member;}},roles:{cache:new Map([["role",role]])}};const gateway=new DiscordMemberRoleGateway({user:{id:"bot"},guilds:{cache:new Map([["guild",guild]])}});const facts=await gateway.getMemberFacts({guildId:"guild",userId:"user",actorId:"actor"});assert.equal(fetched.every(q=>q.force),true);assert.deepEqual(facts.currentRoleIds,["role"]);assert.equal(Object.values(facts).some(v=>v&&typeof v==="object"&&!Array.isArray(v)),true);assert.equal(facts.targetIsBot,false);});
