const test=require("node:test");const assert=require("node:assert/strict");const AutoRoleRule=require("../../src/domain/entities/AutoRoleRule");const{matchesRule,sortRules,buildRoleChangePlan}=require("../../src/domain/policies/AutoRolePolicy");
function rule(overrides={}){return new AutoRoleRule({ruleId:"r1",guildId:"10000000000000001",name:"Rule",trigger:"MEMBER_JOIN",targetRoleIds:["10000000000000010"],...overrides});}
test("rule defaults conflict policy to SKIP_IF_CONFLICT and validates exclusive target",()=>{assert.equal(rule().conflictPolicy,"SKIP_IF_CONFLICT");assert.throws(()=>rule({exclusiveGroup:"g",targetRoleIds:["1","2"]}));});
test("matching requires all required roles and rejects any excluded role",()=>{const r=rule({requiredRoleIds:["a","b"],excludedRoleIds:["x"]});assert.equal(matchesRule(r,{trigger:"MEMBER_JOIN",currentRoleIds:["a","b"]}),true);assert.equal(matchesRule(r,{trigger:"MEMBER_JOIN",currentRoleIds:["a"]}),false);assert.equal(matchesRule(r,{trigger:"MEMBER_JOIN",currentRoleIds:["a","b","x"]}),false);});
test("rules sort priority descending then rule id deterministically",()=>{assert.deepEqual(sortRules([rule({ruleId:"b",priority:5}),rule({ruleId:"c",priority:9}),rule({ruleId:"a",priority:5})]).map(r=>r.ruleId),["c","a","b"]);});
test("existing targets produce immutable no-change plan",()=>{const plan=buildRoleChangePlan(rule(),{userId:"u",currentRoleIds:["10000000000000010"]});assert.equal(plan.changed,false);assert.equal(plan.reasonCode,"ALREADY_ASSIGNED");assert.ok(Object.isFrozen(plan.addRoleIds));});
test("default and keep policies skip exclusive conflict",()=>{for(const conflictPolicy of["SKIP_IF_CONFLICT","KEEP_EXISTING"]){const r=rule({exclusiveGroup:"g",conflictPolicy});const plan=buildRoleChangePlan(r,{userId:"u",currentRoleIds:["old"]},{groupRoleIds:["old"]});assert.equal(plan.changed,false);}});
test("replace lower priority only removes lower owning roles",()=>{const r=rule({exclusiveGroup:"g",conflictPolicy:"REPLACE_LOWER_PRIORITY",priority:10});assert.deepEqual(buildRoleChangePlan(r,{userId:"u",currentRoleIds:["old"]},{groupRoleIds:["old"],owningPriorityByRole:{old:5}}).removeRoleIds,["old"]);assert.equal(buildRoleChangePlan(r,{userId:"u",currentRoleIds:["old"]},{groupRoleIds:["old"],owningPriorityByRole:{old:10}}).changed,false);});
test("explicit removal is disabled unless config enables semantics",()=>{const r=rule({removeRoleIds:["old"]});assert.deepEqual(buildRoleChangePlan(r,{userId:"u",currentRoleIds:["old"]},{removalSemantics:false}).removeRoleIds,[]);assert.deepEqual(buildRoleChangePlan(r,{userId:"u",currentRoleIds:["old"]},{removalSemantics:true}).removeRoleIds,["old"]);});
